version: '3.8'

services:
  web:
    build:
      context: .
    image: gcr.io/leadsmanager01/leadsmanager-web:latest
    command: gunicorn --workers=2 --timeout 180 leadsmanager.wsgi:application --bind 0.0.0.0:${PORT:-8080}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"     

  celery-sample:
    build:
      context: .
    image: gcr.io/leadsmanager01/leadsmanager-celery:latest
    command: celery -A leadsmanager worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=leadsmanager.settings
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT}/0
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_SQL_CONNECTION_NAME=${CLOUD_SQL_CONNECTION_NAME}

  celery:
    build:
      context: .
    image: gcr.io/leadsmanager01/leadsmanager-celery:latest
    command: celery -A leadsmanager worker --loglevel=info

  celery-beat-sample:
    build:
      context: .
    image: gcr.io/leadsmanager01/leadsmanager-celery-beat:latest
    command: celery -A leadsmanager beat --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=leadsmanager.settings
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT}/0
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_SQL_CONNECTION_NAME=${CLOUD_SQL_CONNECTION_NAME}

  celery-beat:
    build:
      context: .
    image: gcr.io/leadsmanager01/leadsmanager-celery-beat:latest
    command: celery -A leadsmanager beat --loglevel=info

  redis-sample:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"  # Default to port 6379
    environment:
      - REDIS_PORT=${REDIS_PORT:-6379}

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"  # Default to port 6379

volumes:
  db_data: