# Generated by Django 5.0.4 on 2024-08-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattribute',
            name='key',
        ),
        migrations.RemoveField(
            model_name='userattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='userattribute',
            name='value1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='value2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
