# Generated by Django 5.0.4 on 2024-08-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_remove_userattribute_key_remove_userattribute_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mail',
        ),
    ]
