# Generated by Django 5.0.4 on 2024-09-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='SimpliRouteData',
        ),
    ]
