# Generated by Django 5.1.1 on 2024-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpisapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="omsdata",
            name="sucursal",
            field=models.CharField(max_length=50),
        ),
    ]
