# Generated by Django 5.1.1 on 2024-09-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpisapp", "0003_omsdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpliroutedata",
            name="tracking_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="OrderTrackingRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oms_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpisapp.omsdata",
                    ),
                ),
                (
                    "simpli_route_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpisapp.simpliroutedata",
                    ),
                ),
            ],
        ),
    ]
