# Generated by Django 5.0.4 on 2024-09-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpisapp', '0004_alter_simpliroutedata_tracking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertrackingrelation',
            name='oms_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpisapp.omsdata'),
        ),
        migrations.AlterField(
            model_name='ordertrackingrelation',
            name='simpli_route_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpisapp.simpliroutedata'),
        ),
    ]
