# Generated by Django 5.0.4 on 2024-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField()),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_y_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('origen', models.CharField(max_length=255)),
                ('sub_origen', models.CharField(max_length=255)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('avance', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('form_id', models.IntegerField()),
                ('submission_id', models.IntegerField(unique=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
