# Generated by Django 5.0.4 on 2024-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField()),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_y_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('origen', models.CharField(max_length=255)),
                ('sub_origen', models.CharField(max_length=255)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('avance', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('contactado', 'Contactado'), ('faltaCotizar', 'Falta cotizar'), ('cotizado', 'Cotizado'), ('interesadoAvanzar', 'Interesados en avanzar'), ('gestionExitosa', 'Gestion exitosa'), ('pospuesto', 'pospuesto'), ('noAvanzo', 'No avanzo'), ('noViable', 'No viable'), ('nuevoCliente', 'Nuevo cliente'), ('negativo', 'Negativo'), ('noDefinido', 'No definido')], max_length=50)),
                ('form_id', models.IntegerField()),
                ('submission_id', models.IntegerField(unique=True)),
                ('data', models.JSONField()),
                ('management_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('contactado', 'Contactado'), ('faltaCotizar', 'Falta cotizar'), ('cotizado', 'Cotizado'), ('interesadoAvanzar', 'Interesados en avanzar'), ('gestionExitosa', 'Gestion exitosa'), ('pospuesto', 'pospuesto'), ('noAvanzo', 'No avanzo'), ('noViable', 'No viable'), ('nuevoCliente', 'Nuevo cliente'), ('negativo', 'Negativo'), ('noDefinido', 'No definido')], max_length=50, null=True)),
                ('new_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('contactado', 'Contactado'), ('faltaCotizar', 'Falta cotizar'), ('cotizado', 'Cotizado'), ('interesadoAvanzar', 'Interesados en avanzar'), ('gestionExitosa', 'Gestion exitosa'), ('pospuesto', 'pospuesto'), ('noAvanzo', 'No avanzo'), ('noViable', 'No viable'), ('nuevoCliente', 'Nuevo cliente'), ('negativo', 'Negativo'), ('noDefinido', 'No definido')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
