# Generated by Django 5.0.4 on 2024-08-23 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0004_campaign_formsubmission_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('contactado', 'Contactado'), ('faltaCotizar', 'Falta cotizar'), ('cotizado', 'Cotizado'), ('interezadoAvanzar', 'Interesados en avanzar'), ('gestionExitosa', 'Gestion exitosa'), ('pospuesto', 'pospuesto'), ('noAvanzo', 'No avanzo'), ('noViable', 'No viable'), ('nuevoCliente', 'Nuevo cliente'), ('negativo', 'Negativo')], max_length=50),
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('contactado', 'Contactado'), ('faltaCotizar', 'Falta cotizar'), ('cotizado', 'Cotizado'), ('interezadoAvanzar', 'Interesados en avanzar'), ('gestionExitosa', 'Gestion exitosa'), ('pospuesto', 'pospuesto'), ('noAvanzo', 'No avanzo'), ('noViable', 'No viable'), ('nuevoCliente', 'Nuevo cliente'), ('negativo', 'Negativo')], max_length=50, null=True)),
                ('new_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('contactado', 'Contactado'), ('faltaCotizar', 'Falta cotizar'), ('cotizado', 'Cotizado'), ('interezadoAvanzar', 'Interesados en avanzar'), ('gestionExitosa', 'Gestion exitosa'), ('pospuesto', 'pospuesto'), ('noAvanzo', 'No avanzo'), ('noViable', 'No viable'), ('nuevoCliente', 'Nuevo cliente'), ('negativo', 'Negativo')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='formsapp.formsubmission')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
