# Generated by Django 5.1.1 on 2024-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formsapp", "0005_alter_formsubmission_estado_leadhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("asignado", "Asignado"),
                    ("contactado", "Contactado"),
                    ("faltaCotizar", "Falta cotizar"),
                    ("cotizado", "Cotizado"),
                    ("interesadoAvanzar", "Interesados en avanzar"),
                    ("gestionExitosa", "Gestion exitosa"),
                    ("pospuesto", "pospuesto"),
                    ("noAvanzo", "No avanzo"),
                    ("noViable", "No viable"),
                    ("nuevoCliente", "Nuevo cliente"),
                    ("negativo", "Negativo"),
                    ("noDefinido", "No definido"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leadhistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("asignado", "Asignado"),
                    ("contactado", "Contactado"),
                    ("faltaCotizar", "Falta cotizar"),
                    ("cotizado", "Cotizado"),
                    ("interesadoAvanzar", "Interesados en avanzar"),
                    ("gestionExitosa", "Gestion exitosa"),
                    ("pospuesto", "pospuesto"),
                    ("noAvanzo", "No avanzo"),
                    ("noViable", "No viable"),
                    ("nuevoCliente", "Nuevo cliente"),
                    ("negativo", "Negativo"),
                    ("noDefinido", "No definido"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leadhistory",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendiente", "Pendiente"),
                    ("asignado", "Asignado"),
                    ("contactado", "Contactado"),
                    ("faltaCotizar", "Falta cotizar"),
                    ("cotizado", "Cotizado"),
                    ("interesadoAvanzar", "Interesados en avanzar"),
                    ("gestionExitosa", "Gestion exitosa"),
                    ("pospuesto", "pospuesto"),
                    ("noAvanzo", "No avanzo"),
                    ("noViable", "No viable"),
                    ("nuevoCliente", "Nuevo cliente"),
                    ("negativo", "Negativo"),
                    ("noDefinido", "No definido"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
